services:
    jitstreamer-eb:
        container_name: jitstreamer-eb
        network_mode: bridge #TODO, is bridge mode possible?
        ports:
            - "9172:9172/tcp"
            - "51869:51869/udp"
        volumes:
            - ./lockdown:/var/lib/lockdown
            - ./wireguard:/etc/wireguard
            - ./jitstreamer.db:/app/jitstreamer.db
        environment:
            - RUST_LOG=debug
            - RUNNER_COUNT=5
            - WIREGUARD_ENDPOINT=jit.isign.ren
            - ALLOW_REGISTRATION=1
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        image: jkcoxson/jitstreamer-eb:latest
        restart: unless-stopped

